### PR TITLE
Tensorboard Version Fix

### PR DESCRIPTION
**Pull request by ASzot**
## Motivation and Context

The `tensorboard` package version was not specified and there are problems with the most recent version of tensor board. This PR specifies the version.

## Types of changes

- Docs change / refactoring / dependency upgrade
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by vincentpierre — APPROVED** [review]

**Comment by erikwijmans** [comment]
What issues are there? And can we fix those? The more recent versions of tensorboard (>=2.8 IIRC) include the new data loader and it's about 100-1000x faster than the old one so we shouldn't be making people use the old one unless we really need to.

**Comment by vincentpierre** [comment]
I think that all packages we have as dependencies should have both a minimum version **AND** a maximum version. Too often will the code break just because a new version of a dependency gets released (including in CI testing). We should only change those versions when there is a new feature that we want/need in the dependency. The time we spend fixing these types of issues is too high IMO.

**Comment by dhruvbatra** [comment]
Agreed wtih Vince. And agreed with Aaron that if a code has stopped serving its utility, we should retire it. If someone wants to reproduce baseline experiments from our ICCV19 paper, then have to use an older version. We don't need to retain that functionality in all future versions.

**Comment by ASzot** [comment]
@erikwijmans There was an installation issue which was causing all tests to fail. I've updated TB to a more recent version that will hopefully work as well.

**Review by vincentpierre — APPROVED** [review]

**Pull request merged**
