### PR TITLE
update black version in pre-commit-config

### PR DESCRIPTION
**Pull request by aclegg3**
## Motivation and Context

Formatting was updated in #1110, but version should also be bumped in the pre-commit config or formatting won't be correct for developer commits.

## How Has This Been Tested

?

## Types of changes

- Docs change / refactoring / dependency upgrade

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by 0mdc — APPROVED** [review]

**Comment by vincentpierre** [comment]
You also need to update the black version [here](https://github.com/facebookresearch/habitat-lab/blob/main/.circleci/config.yml#L23) I believe.

**Comment by vincentpierre** [comment]
You also should select a fixed version here : https://github.com/facebookresearch/habitat-lab/blob/main/.pre-commit-config.yaml#L103 If you set `22.3.0` it will fix the errors, but I think you should set it to `23.1.0` to be consistent

**Comment by aclegg3** [comment]
> Thanks @aclegg3 ! You also need to update the black version [here](https://github.com/facebookresearch/habitat-lab/blob/main/.circleci/config.yml#L23) I believe.

To be clear you are suggesting that we lock the black version in all locations instead of letting it upgrade automatically with future releases like it is now?

**Comment by vincentpierre** [comment]
> To be clear you are suggesting that we lock the black version in all locations instead of letting it upgrade automatically with future releases like it is now?

Yes, or at lest putting a maximum major version so that CI pre-commit does not just randomly break once in a while.

**Review by 0mdc — APPROVED** [review]

**Pull request merged**
