### PR TITLE
Fixed automatic data download outside of git repo

### PR DESCRIPTION
**Pull request by mathfac**
## Motivation and Context
Data downloader works without explicit data-path only inside of git repo. To support usage with PyPi package setting data-path.

## How Has This Been Tested
CI

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by erikwijmans — COMMENTED** [review]
This seems fine for now, but if we want to install things download as part of a package, `<current_dir>/data` probably isn't the right thing as things will get re-downloaded if your current directory changes.

**Comment by mathfac** [comment]
@erikwijmans, maybe have environment variable with data folder path, something like `HABITAT_DATA_PATH`. If that isn't set download to current dir and set the variable.

**Comment by erikwijmans** [comment]
Setting the environment variable won't work as you can't set environment variables for your parent process AFAIK. 

In general I've seen things like `$HOME/.habitat/data` be used, I think MMF does that and I'm pretty sure torchvision does that. I don't love that as it's kinda hard to figure out that's it's doing that and a pain to direct it elsewhere (even if it's configurable it's easy to forget to change it in some config), but I get why it's done.

**Comment by Skylion007** [comment]
> Setting the environment variable won't work as you can't set environment variables for your parent process AFAIK.
> 
> In general I've seen things like `$HOME/.habitat/data` be used, I think MMF does that and I'm pretty sure torchvision does that. I don't love that as it's kinda hard to figure out that's it's doing that and a pain to direct it elsewhere (even if it's configurable it's easy to forget to change it in some config), but I get why it's done.

Agree with @erikwijmans . This is the standard with an ENV variable usually be used to optionally override the location (if your home folder has limited space for instance). TorchVision also does this for example.

**Comment by Skylion007** [comment]
Is this intended to fix the broken CI we have for Habitat-Sim. Or would that require an additional change?

**Comment by mathfac** [comment]
When habitat-lab is pip installed there is no git repo. We need specify the data folder otherwise example with RearrangeTask is throwing the error.

**Comment by mathfac** [comment]
@erikwijmans , @Skylion007 I like the idea with `$HOME/.habitat/data`, but that will require deeper refactoring as we everywhere in configs assume that "<current_dir>/data" is the directory with all the data.  This change may not be needed after https://github.com/facebookresearch/habitat-sim/pull/1369 lands.

**Comment by erikwijmans** [comment]
It's deeper than a 1 line fix, but it isn't that deep and I do think it's worth doing.  If the goal here is to make habitat-lab a package that people can install and plays nicely with other RL training libraries, I think we should have the default be a stable path.  Otherwise users will end up redownloading data or will need to make a trail of symlinks.

**Pull request closed without merging**
