### PR TITLE
added polymetis usage example

### PR DESCRIPTION
**Pull request by laikhtewari**
## Motivation and Context

A jupyter notebook demonstrating how to use habitat with a custom controller through polymetis was created. 
[T122948275](https://www.internalfb.com/intern/tasks/?t=122948275)

## How Has This Been Tested

Running the Jupyter notebook with the correct environment setup shows a waving robot in a specified scene (franka arm in an apartment with defaults)

Note that the following were added to the polymetis conda environment:
    - opencv=4.5.1
    - jupyter

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Skylion007** [comment]
@laikhtewari Can you look into try to make this a colab notebook? See the ones defined in the examples folder for comparison.

**Comment by aclegg3** [comment]
> @laikhtewari Can you look into try to make this a colab notebook? See the ones defined in the examples folder for comparison.

Agreed. We also have automation tools in place to automatically convert to a python script on commit which can be run locally and during CI testing.
Just place the colab notebook in `examples/tutorials/nb_python/`

**Comment by dhruvbatra** [comment]
Agreed. Once it's in that state, we can also add your tutorial to our current set of tutorials: https://aihabitat.org/tutorial/

**Comment by laikhtewari** [comment]
Added issue to convert notebook into colab: https://github.com/facebookresearch/habitat-lab/issues/910

**Review by 1heart — APPROVED** [review]

**Pull request merged**
