### PR TITLE
--[Bug Fix] Address out of date config file extensions.

### PR DESCRIPTION
**Pull request by jturner65**
## Motivation and Context
Updates Hab-Lab to be compatible with recent Hab-Sim breaking changes : 
https://github.com/facebookresearch/habitat-sim/pull/869

## Types of changes

- Docs change / refactoring / dependency upgrade
x- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by Skylion007** [comment]
If it passes, merge it in.

**Comment by jturner65** [comment]
What is causing this timeout?  It happens pretty often on sim as well :(.

**Comment by Skylion007** [comment]
Can you link logs? All the force pushing is covering up which runs actually timed out.

**Comment by Skylion007** [comment]
There is a pytest timeout that says no test can take more than 10 minutes. That can be changed in settings.

**Comment by jturner65** [comment]
It seems arbitrary - sometimes it times out, sometimes it does not.  The most recent was the one that just failed.
https://app.circleci.com/pipelines/github/facebookresearch/habitat-lab/1288/workflows/5b4a285d-296d-4d14-9f1e-2e13b710d416

**Pull request merged**
