### PR TITLE
ECCV 2020: Added Habitat challenge tutorial

### PR DESCRIPTION
**Pull request by mathfac**
## Motivation and Context
ECCV 2020: Added Habitat challenge tutorial

## How Has This Been Tested
Run on EC2 image.

## Types of changes

- Docs change / refactoring / dependency upgrade

### CODE REVIEW

**Comment by Skylion007** [comment]
Corresponding python script for the ipynb is missing.

**Comment by Skylion007** [comment]
Your thing is failed now because you left the tests in for habitat-lab

**Comment by Skylion007** [comment]
@mathfac Frankly, the generated python script has no actual python in it, meaning it can't be tested at all. We may want to just self-host this colab as a github Gist like @eundersander 's tutorial instead of putting it in the Habitat-Lab repo.

**Comment by aclegg3** [comment]
This is hosted as a gist https://colab.research.google.com/gist/mathfac/3c15af549cc4498a0b0f0b84130a7203/eccv2020_habitat_challenge_tutorial.ipynb

**Pull request closed without merging**
