### PR TITLE
[WIP] Bugfix obs transformer 

### PR DESCRIPTION
**Pull request by vincentpierre**
## Motivation and Context

Realized there was no test for obs_transforms. This is a first attempt at doing this.
The test simply makes sure that each individual transform is able to properly modify the observation_space as well as transforming an image with said dimension.

## Types of changes

- Docs change / refactoring / dependency upgrade
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Skylion007** [comment]
There are integration tests wrapped in the baseline trainer .py class, but I agree there should be more unitifed tests. I am also pretty sure most of the cube2equirect etc... have round trip tests as well.

**Comment by Skylion007** [comment]
@vincentpierre No, none of the none-target uuids should be removed. You would need a seperate deleter UUID transform to do that. They can definitely modify the shape of the observation transform. A fully integrated test can be found here: https://github.com/facebookresearch/habitat-lab/blob/e2cb80843f6ddf24ffd3964976a5136963c03568/test/test_baseline_trainers.py#L52 and for the equirect sensors, they can be found here: https://github.com/facebookresearch/habitat-lab/blob/e2cb80843f6ddf24ffd3964976a5136963c03568/test/test_baseline_trainers.py#L128

**Comment by vincentpierre** [comment]
@Skylion007 I saw this integrated test, but I think we need a unit test. The observation output shape is currently NOT the same as the observation space shape (see the CI error). The test only works when the config shape is the same as the observation shape and it does not work in the general case.

**Review by Skylion007 — APPROVED** [review]
Thanks for fixing this @vincentpierre

**Pull request merged**
