### PR TITLE
[Bug Fix] fix the angle between the agent and the object

### PR DESCRIPTION
**Pull request by jimmytyyang**
## Motivation and Context

 This fixes the angle between the agent and the target location

## How Has This Been Tested

 By running interactive_play.py

## Checklist

- [x] My code follows the code style of this project.
- [x] I have updated the documentation if required.
- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [] I have added tests to cover my changes if required.

### CODE REVIEW

**Comment by jimmytyyang** [comment]
Screenshot 2023-04-03 at 9 22 02 AM

**Comment by jimmytyyang** [comment]
Screenshot 2023-04-03 at 11 07 44 AM

**Review by mathfac — APPROVED** [review]
@jimmytyyang do we want to add unit test, to make sure it working right now?

**Review by yvsriram — APPROVED** [review]

**Comment by jimmytyyang** [comment]
Thank you! I added the comments to the picture. Sriram has checked the functionality. and I think it is fine, thank you!

Screenshot 2023-04-06 at 10 18 09 AM

**Pull request merged**
